# apfs_condenser
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/apfs_condenser.8
complete -c apfs_condenser -s s --description 'If compaction succeeds, the snapshot will be deleted.'
complete -c apfs_condenser -s v --description 'Increase verbosity of the output.'
complete -c apfs_condenser -s w --description 'Force the compaction to abort after the supplied timeout in seconds.'

