# automator
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/automator.1
complete -c automator -s D --description 'Set variable name to value for this run of workflow.'
complete -c automator -s i --description 'Set input as the input to workflow.'
complete -c automator -s v --description 'Run in verbose mode.  El Pp.'

