# avconvert
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/avconvert.1
complete -c avconvert -o '\\-source' --description 'The source media file to be converted.'
complete -c avconvert -o '\\-output' --description 'The output movie file to be created.'
complete -c avconvert -o '\\-preset' --description 'Use the specified preset for file conversion.'
complete -c avconvert -o '\\-disableFastStart' --description 'Disable fast-start movie creation.'
complete -c avconvert -o '\\-disableMetadataFilter' --description 'Disable the metadata filter.   Use with caution.'
complete -c avconvert -o '\\-duration' --description 'Trim the output movie to num seconds (decimal allowed).'
complete -c avconvert -o '\\-help' --description 'Print command usage and list available preset names.'
complete -c avconvert -o '\\-multiPass' --description 'Perform a higher quality multi-pass encode in the conversion.'
complete -c avconvert -o '\\-progress' --description 'Display progress during the conversion (default with -v).'
complete -c avconvert -o '\\-replace' --description 'Overwrite the output file, if it already exists.'
complete -c avconvert -o '\\-start' --description 'Skip the first num seconds (decimal allowed) of the source movie.'
complete -c avconvert -o '\\-verbose' --description 'Print additional information about the conversion.'

