# bundle-update
# Autogenerated from man page /usr/share/man/man1/bundle-update.1
complete -c bundle-update -l conservative --description 'Use bundle install conservative update behavior and do not allow shared depen…'
complete -c bundle-update -l ---------------------------------------------------------- --description '1  bundle update --patch            \'foo 1. 4. 5\', \'bar 2. 1.'

