# corelist5
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/corelist5.28.1
complete -c corelist5 -l utils --description 'lists the first version of perl each named utility program was released with .'

