# corelist
# Autogenerated from man page /usr/local/share/man/man1/corelist.1
complete -c corelist -l utils --description 'lists the first version of perl each named utility program was released with .'

