# cron
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/cron.8
complete -c cron -s s --description 'Enable special handling of situations when the GMT offset of the local timezo…'
complete -c cron -s o --description 'Disable the special handling of situations when the GMT offset of the local t…'
complete -c cron -s x --description 'Enable writing of debugging information to standard output.'

