# cupsaccept
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/cupsaccept.8
complete -c cupsaccept -s E --description 'Forces encryption when connecting to the server.'
complete -c cupsaccept -s U --description 'Sets the username that is sent when connecting to the server.'
complete -c cupsaccept -s h --description 'Chooses an alternate server.'
complete -c cupsaccept -s r --description 'Sets the reason string that is shown for a printer that is rejecting jobs.'

