# dctool
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/dctool.1
complete -c dctool -s a --description 'Description of -a flag.'
complete -c dctool -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

