# dnsdomainname
# Autogenerated from man page /usr/local/share/man/man1/dnsdomainname.1
complete -c dnsdomainname -s '?' -l help --description 'give this help list.'
complete -c dnsdomainname -l usage --description 'give a short usage message.'
complete -c dnsdomainname -s V -l version --description 'print program version AUTHOR Written by Simon Josefsson.'

