# dspluginhelperd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/dspluginhelperd.8
complete -c dspluginhelperd -s v --description 'Display the release version.'

