# expand
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/expand.1
complete -c expand -s a --description 'expand ( unexpand only.'
complete -c expand -s t --description 'Set tab stops at column positions tab1 , tab2 , .  , tabn.'

