# fsck_apfs
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/fsck_apfs.8
complete -c fsck_apfs -s q --description 'Causes fsck_apfs to quickly check whether the device is `clean\'.'
complete -c fsck_apfs -s n --description 'Never attempt to repair any damage that is found.'
complete -c fsck_apfs -s y --description 'Always attempt to repair any damage that is found.'
complete -c fsck_apfs -s l --description 'Enable live verification mode.'
complete -c fsck_apfs -s s --description 'Print space verification summary.'
complete -c fsck_apfs -s S --description 'Skip iteration of snapshots (top-level snapshot structures will still be chec…'
complete -c fsck_apfs -s o --description 'Repair overallocations; please do not run an older fsck_apfs on newer systems…'

