# fuser
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/fuser.1
complete -c fuser -s c --description 'The file is treated as a mount point and the utility shall report on any file…'
complete -c fuser -s f --description 'The report shall be only for the named files.'
complete -c fuser -s u --description 'The user name, in parentheses, associated with each process ID written to sta…'

