# gbasenc
# Autogenerated from man page /usr/local/share/man/man1/gbasenc.1
complete -c gbasenc -l base64 --description 'same as \'base64\' program (RFC4648 section 4).'
complete -c gbasenc -l base64url --description 'file- and url-safe base64 (RFC4648 section 5).'
complete -c gbasenc -l base32 --description 'same as \'base32\' program (RFC4648 section 6).'
complete -c gbasenc -l base32hex --description 'extended hex alphabet base32 (RFC4648 section 7).'
complete -c gbasenc -l base16 --description 'hex encoding (RFC4648 section 8).'
complete -c gbasenc -l base2msbf --description 'bit string with most significant bit (msb) first.'
complete -c gbasenc -l base2lsbf --description 'bit string with least significant bit (lsb) first.'
complete -c gbasenc -s d -l decode --description 'decode data.'
complete -c gbasenc -s i -l ignore-garbage --description 'when decoding, ignore non-alphabet characters.'
complete -c gbasenc -s w -l wrap --description 'wrap encoded lines after COLS character (default 76).'
complete -c gbasenc -l z85 --description 'ascii85-like encoding (ZeroMQ spec:32/Z85); when encoding, input length must …'
complete -c gbasenc -l help --description 'display this help and exit.'
complete -c gbasenc -l version --description 'output version information and exit.'

