# gfactor
# Autogenerated from man page /usr/local/share/man/man1/gfactor.1
complete -c gfactor -l help --description 'display this help and exit.'
complete -c gfactor -l version --description 'output version information and exit AUTHOR Written by Paul Rubin, Torbj"orn G…'

