# gfalse
# Autogenerated from man page /usr/local/share/man/man1/gfalse.1
complete -c gfalse -l help --description 'display this help and exit.'
complete -c gfalse -l version --description 'output version information and exit.'

