# gftp
# Autogenerated from man page /usr/local/share/man/man1/gftp.1
complete -c gftp -s 4 -l ipv4 --description 'contact IPv4 hosts.'
complete -c gftp -s 6 -l ipv6 --description 'contact IPv6 hosts.'
complete -c gftp -s A -l active --description 'enable active mode transfer.'
complete -c gftp -s d -l debug --description 'enable debugging output.'
complete -c gftp -s e -l no-edit --description 'disable command line editing.'
complete -c gftp -s g -l no-glob --description 'turn off file name globbing.'
complete -c gftp -s i -l no-prompt --description 'do not prompt during multiple file transfers.'
complete -c gftp -s n -l no-login --description 'do not automatically login to the remote system.'
complete -c gftp -s N -l netrc --description 'select a specific initialization file.'
complete -c gftp -s p -l passive --description 'enable passive mode transfer, default for `pftp\'.'
complete -c gftp -l prompt --description 'print a command line PROMPT (optionally), even if not on a tty.'
complete -c gftp -s t -l trace --description 'enable packet tracing.'
complete -c gftp -s v -l verbose --description 'verbose output.'
complete -c gftp -s '?' -l help --description 'give this help list.'
complete -c gftp -l usage --description 'give a short usage message.'
complete -c gftp -s V -l version --description 'print program version.'

