# gftpd
# Autogenerated from man page /usr/local/share/man/man8/gftpd.8
complete -c gftpd -s 4 -l ipv4 --description 'restrict daemon to IPv4.'
complete -c gftpd -s 6 -l ipv6 --description 'restrict daemon to IPv6.'
complete -c gftpd -s a -l auth --description 'use AUTH for authentication.'
complete -c gftpd -s A -l anonymous-only --description 'server configured for anonymous service only.'
complete -c gftpd -s d -l debug --description 'debug mode.'
complete -c gftpd -s D -l daemon --description 'start the ftpd standalone.'
complete -c gftpd -s l -l logging --description 'increase verbosity of syslog messages.'
complete -c gftpd -l non-rfc2577 --description 'neglect RFC 2577 by giving info on missing users.'
complete -c gftpd -s p -l pidfile --description 'change default location of pidfile.'
complete -c gftpd -s q -l no-version --description 'do not display version in banner.'
complete -c gftpd -s t -l timeout --description 'set default idle timeout.'
complete -c gftpd -s T -l max-timeout --description 'reset maximum value of timeout allowed.'
complete -c gftpd -s u -l umask --description 'set default umask P AUTH can be one of the following:.'
complete -c gftpd -s '?' -l help --description 'give this help list.'
complete -c gftpd -l usage --description 'give a short usage message.'
complete -c gftpd -s V -l version --description 'print program version.'

