# ggroups
# Autogenerated from man page /usr/local/share/man/man1/ggroups.1
complete -c ggroups -l help --description 'display this help and exit.'
complete -c ggroups -l version --description 'output version information and exit AUTHOR Written by David MacKenzie and Jam…'

