# ghead
# Autogenerated from man page /usr/local/share/man/man1/ghead.1
complete -c ghead -s c -l bytes --description 'print the first NUM bytes of each file; with the leading \'-\', print all but t…'
complete -c ghead -s n -l lines --description 'print the first NUM lines instead of the first 10; with the leading \'-\', prin…'
complete -c ghead -s q -l quiet -l silent --description 'never print headers giving file names.'
complete -c ghead -s v -l verbose --description 'always print headers giving file names.'
complete -c ghead -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c ghead -l help --description 'display this help and exit.'
complete -c ghead -l version --description 'output version information and exit.'

