# ghostname
# Autogenerated from man page /usr/local/share/man/man1/ghostname.1
complete -c ghostname -s a -l aliases --description 'alias names.'
complete -c ghostname -s d -l domain --description 'DNS domain name.'
complete -c ghostname -s f -l fqdn -l long --description 'DNS host name or FQDN.'
complete -c ghostname -s F -l file --description 'set host name or NIS domain name from FILE.'
complete -c ghostname -s i -l ip-addresses --description 'addresses for the host name.'
complete -c ghostname -s s -l short --description 'short host name.'
complete -c ghostname -s y -l yp -l nis --description 'NIS/YP domain name.'
complete -c ghostname -s '?' -l help --description 'give this help list.'
complete -c ghostname -l usage --description 'give a short usage message.'
complete -c ghostname -s V -l version --description 'print program version.'

