# ginetd
# Autogenerated from man page /usr/local/share/man/man8/ginetd.8
complete -c ginetd -s d -l debug --description 'turn on debugging, run in foreground mode.'
complete -c ginetd -l environment --description 'pass local and remote socket information in environment variables.'
complete -c ginetd -s p -l pidfile --description 'override pidfile (default: "/usr/local/var/run/inetd. pid").'
complete -c ginetd -l resolve --description 'resolve IP addresses when setting environment variables (see --environment).'
complete -c ginetd -s R -l rate --description 'maximum invocation rate (per minute).'
complete -c ginetd -s '?' -l help --description 'give this help list.'
complete -c ginetd -l usage --description 'give a short usage message.'
complete -c ginetd -s V -l version --description 'print program version.'

