# git-am
# Autogenerated from man page /usr/local/share/man/man1/git-am.1
complete -c git-am -l rerere-autoupdate -l no-rerere-autoupdate --description 'Allow the rerere mechanism to update the index with the result of auto-confli…'

