# git-multi-pack-index
# Autogenerated from man page /usr/local/share/man/man1/git-multi-pack-index.1
complete -c git-multi-pack-index -l batch-size --description 'argument is zero, then create a pack containing all objects referenced by the…'

