# git-send-email
# Autogenerated from man page /usr/local/share/man/man1/git-send-email.1
complete -c git-send-email -l 'no-[to' --description 'Clears any list of "To:", "Cc:", "Bcc:" addresses previously set via config.'
complete -c git-send-email -l no-identity --description 'Clears the previously read value of sendemail.'

