# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l output --description 'Output to a specific file instead of stdout.'
complete -c git-format-patch -l output-indicator-new -l output-indicator-old -l output-indicator-context --description 'Specify the character used to indicate new, old or context lines in the gener…'
complete -c git-format-patch -l cumulative --description 'Synonym for --dirstat=cumulative.'
complete -c git-format-patch -l dirstat-by-file --description 'Synonym for --dirstat=files,param1,param2.'
complete -c git-format-patch -l rename-empty --description 'Whether to use empty blobs as rename source.'
complete -c git-format-patch -l no-notes --description 'Append the notes (see git-notes(1)) for the commit after the three-dash line.'
complete -c git-format-patch -l patch --description '.'
complete -c git-format-patch -o 'X[<param1' --description '.'

