# git-diff-tree
# Autogenerated from man page /usr/local/share/man/man1/git-diff-tree.1
complete -c git-diff-tree -l output --description 'Output to a specific file instead of stdout.'
complete -c git-diff-tree -l output-indicator-new -l output-indicator-old -l output-indicator-context --description 'Specify the character used to indicate new, old or context lines in the gener…'
complete -c git-diff-tree -l cumulative --description 'Synonym for --dirstat=cumulative.'
complete -c git-diff-tree -l dirstat-by-file --description 'Synonym for --dirstat=files,param1,param2.'
complete -c git-diff-tree -l rename-empty --description 'Whether to use empty blobs as rename source.'
complete -c git-diff-tree -l combined-all-paths --description 'This flag causes combined diffs (used for merge commits) to list the name of …'
complete -c git-diff-tree -o 'X[<param1' --description '.'

