# git-checkout
# Autogenerated from man page /usr/local/share/man/man1/git-checkout.1
complete -c git-checkout -l no-progress --description 'Progress status is reported on the standard error stream by default when it i…'
complete -c git-checkout -l guess --description 'If <branch> is not found but there does exist a tracking branch in exactly on…'
complete -c git-checkout -l overwrite-ignore -l no-overwrite-ignore --description 'Silently overwrite ignored files when switching branches.'
complete -c git-checkout -l no-recurse-submodules --description 'Using --recurse-submodules will update the content of all initialized submodu…'
complete -c git-checkout -l overlay -l no-overlay --description 'In the default overlay mode, git checkout never removes files from the index …'

