# git-fast-export
# Autogenerated from man page /usr/local/share/man/man1/git-fast-export.1
complete -c git-fast-export -l mark-tags --description 'In addition to labelling blobs and commits with mark ids, also label tags.'
complete -c git-fast-export -l reencode --description 'Specify how to handle encoding header in commit objects.'

