# git-clone
# Autogenerated from man page /usr/local/share/man/man1/git-clone.1
complete -c git-clone -l server-option --description 'Transmit the given string to the server when communicating using protocol ver…'
complete -c git-clone -l remote-submodules --description 'All submodules which are cloned will use the status of the submodule\\(cqs rem…'
complete -c git-clone -l remote --description 'to git submodule update.'

