# git-blame
# Autogenerated from man page /usr/local/share/man/man1/git-blame.1
complete -c git-blame -l ignore-rev --description 'Ignore changes made by the revision when assigning blame, as if the change ne…'
complete -c git-blame -l ignore-revs-file --description 'Ignore revisions listed in file, which must be in the same format as an fsck.'

