# git-diff
# Autogenerated from man page /usr/local/share/man/man1/git-diff.1
complete -c git-diff -l output --description 'Output to a specific file instead of stdout.'
complete -c git-diff -l output-indicator-new -l output-indicator-old -l output-indicator-context --description 'Specify the character used to indicate new, old or context lines in the gener…'
complete -c git-diff -l cumulative --description 'Synonym for --dirstat=cumulative.'
complete -c git-diff -l dirstat-by-file --description 'Synonym for --dirstat=files,param1,param2.'
complete -c git-diff -l rename-empty --description 'Whether to use empty blobs as rename source.'
complete -c git-diff -o 'X[<param1' --description '.'

