# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
complete -c git-rebase -l keep-base --description 'Set the starting point at which to create the new commits to the merge base o…'
complete -c git-rebase -l rerere-autoupdate -l no-rerere-autoupdate --description 'Allow the rerere mechanism to update the index with the result of auto-confli…'

