# git-cherry-pick
# Autogenerated from man page /usr/local/share/man/man1/git-cherry-pick.1
complete -c git-cherry-pick -l cleanup --description 'This option determines how the commit message will be cleaned up before being…'
complete -c git-cherry-pick -l rerere-autoupdate -l no-rerere-autoupdate --description 'Allow the rerere mechanism to update the index with the result of auto-confli…'
complete -c git-cherry-pick -l skip --description '.'

