# git-merge
# Autogenerated from man page /usr/local/share/man/man1/git-merge.1
complete -c git-merge -l cleanup --description 'This option determines how the merge message will be cleaned up before commit…'
complete -c git-merge -l no-verify --description 'This option bypasses the pre-merge and commit-msg hooks.'
complete -c git-merge -l no-rerere-autoupdate --description 'Allow the rerere mechanism to update the index with the result of auto-confli…'
complete -c git-merge -l overwrite-ignore -l no-overwrite-ignore --description 'Silently overwrite ignored files from the merge result.'
complete -c git-merge -l quit --description 'Forget about the current merge in progress.'

