# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
complete -c git-pull -l cleanup --description 'This option determines how the merge message will be cleaned up before commit…'
complete -c git-pull -l no-verify --description 'This option bypasses the pre-merge and commit-msg hooks.'
complete -c git-pull -l show-forced-updates --description 'By default, git checks if a branch is force-updated during fetch.'
complete -c git-pull -l no-show-forced-updates --description 'By default, git checks if a branch is force-updated during fetch.'

