# git-show
# Autogenerated from man page /usr/local/share/man/man1/git-show.1
complete -c git-show -l output --description '.'
complete -c git-show -l output-indicator-new -l output-indicator-old -l output-indicator-context --description '.'
complete -c git-show -o 'X[<param1' --description '.'
complete -c git-show -l cumulative --description '.'
complete -c git-show -l dirstat-by-file --description '.'
complete -c git-show -l rename-empty --description '.'

