# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
complete -c git-log -l alternate-refs --description 'Pretend as if all objects mentioned as ref tips of alternate repositories wer…'
complete -c git-log -l combined-all-paths --description 'This flag causes combined diffs (used for merge commits) to list the name of …'
complete -c git-log -l output --description '.'
complete -c git-log -l output-indicator-new -l output-indicator-old -l output-indicator-context --description '.'
complete -c git-log -o 'X[<param1' --description '.'
complete -c git-log -l cumulative --description '.'
complete -c git-log -l dirstat-by-file --description '.'
complete -c git-log -l rename-empty --description '.'

