# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l no-ahead-behind --description 'is given.  statusHints.'
complete -c git-config -l ignore-revs-file --description 'blame. markUnblamables.'
complete -c git-config -l split --description 'option, most executions will create a very small commit-graph file on top of …'
complete -c git-config -l no-show-forced-updates --description 'in git-fetch(1) and git-pull(1) commands.  Defaults to true.  fetch. parallel.'
complete -c git-config -l multiple --description 'option of git-fetch(1) is in effect).'
complete -c git-config -l notes --description 'option to format-patch.'
complete -c git-config -l no-notes --description '.'
complete -c git-config -l depth --description 'option when.'
complete -c git-config -l aggressive --description 'isn\'t in use.'
complete -c git-config -l window --description 'of 10.'
complete -c git-config -l no-use-mailmap --description 'mailinfo. scissors.'
complete -c git-config -l ahead-behind --description 'and false to enable.'

