# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
complete -c git-fetch -l auto-gc --description 'Run git gc --auto at the end to perform garbage collection if needed.'
complete -c git-fetch -l set-upstream --description 'If the remote is fetched successfully, pull and add upstream (tracking) refer…'
complete -c git-fetch -l show-forced-updates --description 'By default, git checks if a branch is force-updated during fetch.'
complete -c git-fetch -l no-show-forced-updates --description 'By default, git checks if a branch is force-updated during fetch.'

