# git-commit-graph
# Autogenerated from man page /usr/local/share/man/man1/git-commit-graph.1
complete -c git-commit-graph -l progress --description 'Turn progress on/off explicitly.'
complete -c git-commit-graph -l split --description 'option, write the commit-graph as a chain of multiple commit-graph files stor…'
complete -c git-commit-graph -l size-multiple --description 'is not specified, let X equal 2.'
complete -c git-commit-graph -l max-commits --description 'is specified with M a positive integer, and the new tip file would have more …'
complete -c git-commit-graph -l expire-time --description 'is not specified, let datetime be the current time.'
complete -c git-commit-graph -l shallow --description 'option, only check the tip commit-graph file in a chain of split commit-graph…'

