# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
complete -c git-rev-list -l alternate-refs --description 'Pretend as if all objects mentioned as ref tips of alternate repositories wer…'
complete -c git-rev-list -l object-names --description 'Only useful with --objects; print the names of the object IDs that are found.'
complete -c git-rev-list -l no-object-names --description 'Only useful with --objects; does not print the names of the object IDs that a…'

