# glink
# Autogenerated from man page /usr/local/share/man/man1/glink.1
complete -c glink -l help --description 'display this help and exit.'
complete -c glink -l version --description 'output version information and exit AUTHOR Written by Michael Stone.'

