# glogger
# Autogenerated from man page /usr/local/share/man/man1/glogger.1
complete -c glogger -s 4 -l ipv4 --description 'use IPv4 for logging to host.'
complete -c glogger -s 6 -l ipv6 --description 'use IPv6 with a host target.'
complete -c glogger -s f -l file --description 'log the content of FILE.'
complete -c glogger -s h -l host --description 'log to HOST instead of to the default \\,/dev/log\\/.'
complete -c glogger -s i -l id --description 'log the process id with every line.'
complete -c glogger -s p -l priority --description 'log with priority PRI.'
complete -c glogger -s s -l stderr --description 'copy the message to stderr.'
complete -c glogger -s S -l source --description 'set source IP address.'
complete -c glogger -s t -l tag --description 'prepend every line with TAG.'
complete -c glogger -s u -l unix --description 'log to UNIX socket SOCK instead of \\,/dev/log\\/.'
complete -c glogger -s '?' -l help --description 'give this help list.'
complete -c glogger -l usage --description 'give a short usage message.'
complete -c glogger -s V -l version --description 'print program version.'

