# gmkfifo
# Autogenerated from man page /usr/local/share/man/man1/gmkfifo.1
complete -c gmkfifo -s m -l mode --description 'set file permission bits to MODE, not a=rw - umask.'
complete -c gmkfifo -s Z --description 'set the SELinux security context to default type.'
complete -c gmkfifo -l context --description 'like -Z, or if CTX is specified then set the SELinux or SMACK security contex…'
complete -c gmkfifo -l help --description 'display this help and exit.'
complete -c gmkfifo -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

