# gmktemp
# Autogenerated from man page /usr/local/share/man/man1/gmktemp.1
complete -c gmktemp -s d -l directory --description 'create a directory, not a file.'
complete -c gmktemp -s u -l dry-run --description 'do not create anything; merely print a name (unsafe).'
complete -c gmktemp -s q -l quiet --description 'suppress diagnostics about file/dir-creation failure.'
complete -c gmktemp -l suffix --description 'append SUFF to TEMPLATE; SUFF must not contain a slash.'
complete -c gmktemp -s p -l tmpdir --description 'interpret TEMPLATE relative to DIR; if DIR is not specified, use $TMPDIR if s…'
complete -c gmktemp -s t --description 'interpret TEMPLATE as a single file name component, relative to a directory: …'
complete -c gmktemp -l help --description 'display this help and exit.'
complete -c gmktemp -l version --description 'output version information and exit AUTHOR Written by Jim Meyering and Eric B…'

