# grcp
# Autogenerated from man page /usr/local/share/man/man1/grcp.1
complete -c grcp -s 4 -l ipv4 --description 'use only IPv4.'
complete -c grcp -s 6 -l ipv6 --description 'use only IPv6.'
complete -c grcp -s d -l target-directory --description 'copy all SOURCE arguments into DIRECTORY.'
complete -c grcp -s f -l from --description 'copying from remote host (server use only).'
complete -c grcp -s p -l preserve --description 'attempt to preserve (duplicate) in its copies the modification times and mode…'
complete -c grcp -s r -l recursive --description 'if any of the source files are directories, copies each subtree rooted at tha…'
complete -c grcp -s t -l to --description 'copying to remote host (server use only).'
complete -c grcp -s '?' -l help --description 'give this help list.'
complete -c grcp -l usage --description 'give a short usage message.'
complete -c grcp -s V -l version --description 'print program version.'

