# grexecd
# Autogenerated from man page /usr/local/share/man/man8/grexecd.8
complete -c grexecd -s l -l logging --description 'logging of requests and errors.'
complete -c grexecd -s '?' -l help --description 'give this help list.'
complete -c grexecd -l usage --description 'give a short usage message.'
complete -c grexecd -s V -l version --description 'print program version AUTHOR Written by many authors.'

