# grexec
# Autogenerated from man page /usr/local/share/man/man1/grexec.1
complete -c grexec -s 4 -l ipv4 --description 'Use IPv4 address space.'
complete -c grexec -s 6 -l ipv6 --description 'Use IPv6 address space.'
complete -c grexec -s a -l ipany --description 'Allow any address family.  (default).'
complete -c grexec -s e -l error --description 'Specify a TCP port to use for stderr.'
complete -c grexec -s h -l host --description 'Specify the host.'
complete -c grexec -s n -l noerr --description 'Disable the stderr stream.'
complete -c grexec -s p -l password --description 'Specify the password.'
complete -c grexec -s P -l port --description 'Specify the port to connect to.'
complete -c grexec -s u -l user --description 'Specify the user.'
complete -c grexec -s '?' -l help --description 'give this help list.'
complete -c grexec -l usage --description 'give a short usage message.'
complete -c grexec -s V -l version --description 'print program version.'

