# grlogin
# Autogenerated from man page /usr/local/share/man/man1/grlogin.1
complete -c grlogin -s 4 -l ipv4 --description 'use only IPv4.'
complete -c grlogin -s 6 -l ipv6 --description 'use only IPv6.'
complete -c grlogin -s 8 -l 8-bit --description 'allows an eight-bit input data path at all times.'
complete -c grlogin -s d -l debug --description 'set the SO_DEBUG option.'
complete -c grlogin -s e -l escape --description 'allows user specification of the escape character, which is ``~\'\' by default.'
complete -c grlogin -s E -l no-escape --description 'stops any character from being recognized as an escape character.'
complete -c grlogin -s l -l user --description 'run as USER on the remote system.'
complete -c grlogin -s '?' -l help --description 'give this help list.'
complete -c grlogin -l usage --description 'give a short usage message.'
complete -c grlogin -s V -l version --description 'print program version.'

