# grm
# Autogenerated from man page /usr/local/share/man/man1/grm.1
complete -c grm -s f -l force --description 'ignore nonexistent files and arguments, never prompt.'
complete -c grm -s i --description 'prompt before every removal.'
complete -c grm -s I --description 'prompt once before removing more than three files, or when removing recursive…'
complete -c grm -l interactive --description 'prompt according to WHEN: never, once (-I), or always (-i); without WHEN, pro…'
complete -c grm -l one-file-system --description 'when removing a hierarchy recursively, skip any directory that is on a file s…'
complete -c grm -l no-preserve-root --description 'do not treat \'/\' specially.'
complete -c grm -l preserve-root --description 'do not remove \'/\' (default); with \'all\', reject any command line argument on …'
complete -c grm -s r -s R -l recursive --description 'remove directories and their contents recursively.'
complete -c grm -s d -l dir --description 'remove empty directories.'
complete -c grm -s v -l verbose --description 'explain what is being done.'
complete -c grm -l help --description 'display this help and exit.'
complete -c grm -l version --description 'output version information and exit .'

