# grsh
# Autogenerated from man page /usr/local/share/man/man1/grsh.1
complete -c grsh -s 4 -l ipv4 --description 'use only IPv4.'
complete -c grsh -s 6 -l ipv6 --description 'use only IPv6.'
complete -c grsh -s 8 -l 8-bit --description 'allows an eight-bit input data path at all times.'
complete -c grsh -s d -l debug --description 'turns on socket debugging (see setsockopt(2)).'
complete -c grsh -s e -l escape --description 'allows user specification of the escape character (``~\'\' by default).'
complete -c grsh -s l -l user --description 'run as USER on the remote system.'
complete -c grsh -s n -l no-input --description 'use \\,/dev/null\\/ as input.'
complete -c grsh -s '?' -l help --description 'give this help list.'
complete -c grsh -l usage --description 'give a short usage message.'
complete -c grsh -s V -l version --description 'print program version.'

