# grshd
# Autogenerated from man page /usr/local/share/man/man8/grshd.8
complete -c grshd -s a -l verify-hostname --description 'ask hostname for verification.'
complete -c grshd -s l -l no-rhosts --description 'ignore . rhosts file.'
complete -c grshd -s L -l log-sessions --description 'log successful logins.'
complete -c grshd -s n -l no-keepalive --description 'do not set SO_KEEPALIVE.'
complete -c grshd -s r -l reverse-required --description 'require reverse resolving of remote host IP.'
complete -c grshd -s '?' -l help --description 'give this help list.'
complete -c grshd -l usage --description 'give a short usage message.'
complete -c grshd -s V -l version --description 'print program version AUTHOR Written by many authors.'

