# gtalk
# Autogenerated from man page /usr/local/share/man/man1/gtalk.1
complete -c gtalk -s '?' -l help --description 'give this help list.'
complete -c gtalk -l usage --description 'give a short usage message.'
complete -c gtalk -s V -l version --description 'print program version AUTHOR Written by Kipp Hickman, Clem Cole, and Peter Mo…'

