# gtalkd
# Autogenerated from man page /usr/local/share/man/man8/gtalkd.8
complete -c gtalkd -s a -l acl --description 'read site-wide ACLs from FILE.'
complete -c gtalkd -s d -l debug --description 'enable debugging .'
complete -c gtalkd -s l -l logging --description 'enable more syslog reporting.'
complete -c gtalkd -s r -l request-ttl --description 'set request time-to-live value to SECONDS.'
complete -c gtalkd -s S -l strict-policy --description 'apply strict ACL policy.'
complete -c gtalkd -s t -l timeout --description 'set timeout value to SECONDS.'
complete -c gtalkd -s '?' -l help --description 'give this help list.'
complete -c gtalkd -l usage --description 'give a short usage message.'
complete -c gtalkd -s i -l idle-timeout --description '.'
complete -c gtalkd -s V -l version --description 'print program version.'

