# gtelnetd
# Autogenerated from man page /usr/local/share/man/man8/gtelnetd.8
complete -c gtelnetd -s D -l debug --description 'set debugging level.'
complete -c gtelnetd -s E -l exec-login --description 'set program to be executed instead of \\,/usr/bin/login\\/.'
complete -c gtelnetd -s h -l no-hostinfo --description 'do not print host information before login has been completed.'
complete -c gtelnetd -s l -l linemode --description 'set line mode.'
complete -c gtelnetd -s n -l no-keepalive --description 'disable TCP keep-alives.'
complete -c gtelnetd -s U -l reverse-lookup --description 'refuse connections from addresses that cannot be mapped back into a symbolic …'
complete -c gtelnetd -s '?' -l help --description 'give this help list.'
complete -c gtelnetd -l usage --description 'give a short usage message.'
complete -c gtelnetd -s V -l version --description 'print program version.'

