# gtelnet
# Autogenerated from man page /usr/local/share/man/man1/gtelnet.1
complete -c gtelnet -s 4 -l ipv4 --description 'use only IPv4.'
complete -c gtelnet -s 6 -l ipv6 --description 'use only IPv6.'
complete -c gtelnet -s 8 -l binary --description 'use an 8-bit data transmission.'
complete -c gtelnet -s a -l login --description 'attempt automatic login.'
complete -c gtelnet -s c -l no-rc --description 'do not read the user\'s . telnetrc file.'
complete -c gtelnet -s d -l debug --description 'turn on debugging.'
complete -c gtelnet -s e -l escape --description 'use CHAR as an escape character.'
complete -c gtelnet -s E -l no-escape --description 'use no escape character.'
complete -c gtelnet -s K -l no-login --description 'do not automatically login to the remote system.'
complete -c gtelnet -s l -l user --description 'attempt automatic login as USER.'
complete -c gtelnet -s L -l binary-output --description 'use an 8-bit data transmission for output only.'
complete -c gtelnet -s n -l trace --description 'record trace information into FILE.'
complete -c gtelnet -s r -l rlogin --description 'use a user-interface similar to rlogin.'
complete -c gtelnet -s '?' -l help --description 'give this help list.'
complete -c gtelnet -l usage --description 'give a short usage message.'
complete -c gtelnet -s V -l version --description 'print program version.'

