# gtftp
# Autogenerated from man page /usr/local/share/man/man1/gtftp.1
complete -c gtftp -s v -l verbose --description 'verbose output.'
complete -c gtftp -s '?' -l help --description 'give this help list.'
complete -c gtftp -l usage --description 'give a short usage message.'
complete -c gtftp -s V -l version --description 'print program version AUTHOR Written by many authors.'

