# gtftpd
# Autogenerated from man page /usr/local/share/man/man8/gtftpd.8
complete -c gtftpd -s l -l logging --description 'enable logging.'
complete -c gtftpd -s n -l nonexistent --description 'supress negative acknowledgement of requests for nonexistent relative filenam…'
complete -c gtftpd -s g -l group --description 'set explicit group of process owner, used with \'-s\'.'
complete -c gtftpd -s s -l secure-dir --description 'change root directory to DIR before searching and serving content.'
complete -c gtftpd -s u -l user --description 'set name of process owner, used with \'-s\' and defaults to \'nobody\'.'
complete -c gtftpd -s '?' -l help --description 'give this help list.'
complete -c gtftpd -l usage --description 'give a short usage message.'
complete -c gtftpd -s V -l version --description 'print program version.'

