# gtimeout
# Autogenerated from man page /usr/local/share/man/man1/gtimeout.1
complete -c gtimeout -s v -l verbose --description 'diagnose to stderr any signal sent upon timeout.'
complete -c gtimeout -l help --description 'display this help and exit.'
complete -c gtimeout -l preserve-status --description 'exit with the same status as COMMAND, even when the command times out.'
complete -c gtimeout -l foreground --description 'when not running timeout directly from a shell prompt, allow COMMAND to read …'
complete -c gtimeout -s k -l kill-after --description 'also send a KILL signal if COMMAND is still running this long after the initi…'
complete -c gtimeout -s s -l signal --description 'specify the signal to be sent on timeout; SIGNAL may be a name like \'HUP\' or …'
complete -c gtimeout -l version --description 'output version information and exit.'

