# gtraceroute
# Autogenerated from man page /usr/local/share/man/man1/gtraceroute.1
complete -c gtraceroute -s f -l first-hop --description 'set initial hop distance, i. e. , time-to-live.'
complete -c gtraceroute -s g -l gateways --description 'list of gateways for loose source routing.'
complete -c gtraceroute -s I -l icmp --description 'use ICMP ECHO as probe.'
complete -c gtraceroute -s m -l max-hop --description 'set maximal hop count (default: 64).'
complete -c gtraceroute -s M -l type --description 'use METHOD (`icmp\' or `udp\') for traceroute operations, defaulting to `udp\'.'
complete -c gtraceroute -s p -l port --description 'use destination PORT port (default: 33434).'
complete -c gtraceroute -s q -l tries --description 'send NUM probe packets per hop (default: 3).'
complete -c gtraceroute -l resolve-hostnames --description 'resolve hostnames.'
complete -c gtraceroute -s t -l tos --description 'set type of service (TOS) to NUM.'
complete -c gtraceroute -s w -l wait --description 'wait NUM seconds for response (default: 3).'
complete -c gtraceroute -s '?' -l help --description 'give this help list.'
complete -c gtraceroute -l usage --description 'give a short usage message.'
complete -c gtraceroute -s V -l version --description 'print program version.'

