# gtsort
# Autogenerated from man page /usr/local/share/man/man1/gtsort.1
complete -c gtsort -l help --description 'display this help and exit.'
complete -c gtsort -l version --description 'output version information and exit AUTHOR Written by Mark Kettenis.'

