# gtty
# Autogenerated from man page /usr/local/share/man/man1/gtty.1
complete -c gtty -s s -l silent -l quiet --description 'print nothing, only return an exit status.'
complete -c gtty -l help --description 'display this help and exit.'
complete -c gtty -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

