# gunlink
# Autogenerated from man page /usr/local/share/man/man1/gunlink.1
complete -c gunlink -l help --description 'display this help and exit.'
complete -c gunlink -l version --description 'output version information and exit AUTHOR Written by Michael Stone.'

