# guptime
# Autogenerated from man page /usr/local/share/man/man1/guptime.1
complete -c guptime -l help --description 'display this help and exit.'
complete -c guptime -l version --description 'output version information and exit AUTHOR Written by Joseph Arceneaux, David…'

