# guucpd
# Autogenerated from man page /usr/local/share/man/man8/guucpd.8
complete -c guucpd -s u -l uucico --description 'location of uucico executable, replacing default at \\,/usr/local/libexec/uucp…'
complete -c guucpd -s '?' -l help --description 'give this help list.'
complete -c guucpd -l usage --description 'give a short usage message.'
complete -c guucpd -s V -l version --description 'print program version.'

