# gwc
# Autogenerated from man page /usr/local/share/man/man1/gwc.1
complete -c gwc -s c -l bytes --description 'print the byte counts.'
complete -c gwc -s m -l chars --description 'print the character counts.'
complete -c gwc -s l -l lines --description 'print the newline counts.'
complete -c gwc -l files0-from --description 'read input from the files specified by NUL-terminated names in file F; If F i…'
complete -c gwc -s L -l max-line-length --description 'print the maximum display width.'
complete -c gwc -s w -l words --description 'print the word counts.'
complete -c gwc -l help --description 'display this help and exit.'
complete -c gwc -l version --description 'output version information and exit AUTHOR Written by Paul Rubin and David Ma…'

