# gyes
# Autogenerated from man page /usr/local/share/man/man1/gyes.1
complete -c gyes -l help --description 'display this help and exit.'
complete -c gyes -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

