# h2ph5
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/h2ph5.28.1
complete -c h2ph5 -s e --description 'If an error is encountered during conversion, output file will be removed and…'

