# iostat
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/iostat.8
complete -c iostat -o '?\\&' --description 'Display a usage statement and exit.'
complete -c iostat -s c --description 'Repeat the display count times.'
complete -c iostat -s C --description 'Display CPU statistics.  This is on by default, unless d is specified.'
complete -c iostat -s d --description 'Display only device statistics.'
complete -c iostat -s I --description 'Display total statistics for a given time period, rather than average statist…'
complete -c iostat -s K --description 'In the blocks transferred display (-o), display block count in kilobytes rath…'
complete -c iostat -s n --description 'Display up to devs number of devices.'
complete -c iostat -s o --description 'Display old-style iostat device statistics.'
complete -c iostat -s T --description 'Display TTY statistics.  This is on by default, unless d is specified.'
complete -c iostat -s U --description 'Display system load averages.  This is on by default, unless d is specified.'
complete -c iostat -s w --description 'Pause wait seconds between each display.'

