# kcc
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/kcc.1
complete -c kcc -l version --description 'version information.'
complete -c kcc -l help --description 'help El SEE ALSO kdestroy 1, kinit 1.'

