# kextd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/kextd.8
complete -c kextd -s c --description 'Ignore any repository cache files and scan all kext bundles to gather informa…'
complete -c kextd -s d --description 'Debug mode; print messages to stdout/stderr rather than the system log.'
complete -c kextd -s h --description 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextd -s q --description 'Quiet mode; log no informational or error messages.'
complete -c kextd -s v --description 'Verbose mode; print information about program operation.'
complete -c kextd -s x --description 'Run kextd in safe boot mode (indicating startup with the Shift key held down).'

