# leaks
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/leaks.1
complete -c leaks -o list --description 'Print the leaks as a list ("classic"-style) rather than as a tree.'
complete -c leaks -o groupByType --description 'When printing a tree of leaked objects, group the children of a node in the t…'
complete -c leaks -o nocontext --description 'Do not print the string or hex representation of leaked memory.'
complete -c leaks -o nostacks --description 'Do not print backtraces of leaked blocks even if the target process has the M…'
complete -c leaks -o nosources --description 'Do not print sourceFile:lineNumber in backtraces.'
complete -c leaks -o quiet --description 'Do not print process description header or binary image list.'
complete -c leaks -o exclude --description 'Exclude leaked blocks whose backtraces include the specified symbol.'
complete -c leaks -o traceTree --description 'Print a reverse tree of references, from the given block up to the process \'r…'
complete -c leaks -o outputGraph --description 'Generate a memory graph file containing information about all VM and malloc n…'
complete -c leaks -o fullContent --description 'When generating a memory graph file, include descriptions of the content of v…'
complete -c leaks -o atExit --description 'Launches the specified command and runs leaks leaks when that process exits.'

