# lipo
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/lipo.1
complete -c lipo -o arch --description 'Tells  lipo that  input_file contains the specified architecture type.'
complete -c lipo -o hideARM64 --description 'When creating a universal binary including both 32-bit and 64-bit ARM files, …'
complete -c lipo -o output --description 'Commands that create new files write to the output file specified by the  -ou…'
complete -c lipo -o archs --description 'Display only the architecture names present in a single input file.'
complete -c lipo -o create -o arch_blank --description 'Create one universal output file from one or more input files.'
complete -c lipo -o detailed_info --description 'Display a detailed list of the architecture types in the input universal file…'
complete -c lipo -o extract -o extract --description 'Take one universal input file and copy the arch_type from that universal file…'
complete -c lipo -o extract_family -o extract_family --description 'Take one universal input file and copy all of the arch_type s for the family …'
complete -c lipo -o info --description 'Display a brief description of each input file along with the names of each a…'
complete -c lipo -o remove -o remove --description 'Take one universal input file and remove the arch_type from that universal fi…'
complete -c lipo -o replace -o replace --description 'Take one universal input file; in the output file, replace the arch_type cont…'
complete -c lipo -o thin --description 'Take one input file and create a thin output file with the specified arch_typ…'
complete -c lipo -o verify_arch --description 'Take one input file and verify the specified arch_type s are present in the f…'
complete -c lipo -o segalign --description 'Set the segment alignment of the specified arch_type when creating a universa…'

