# lprm
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/lprm.1
complete -c lprm -s E --description 'Forces encryption when connecting to the server.'
complete -c lprm -s P --description 'Specifies the destination printer or class.'
complete -c lprm -s U --description 'Specifies an alternate username.'
complete -c lprm -s h --description 'Specifies an alternate server.'

