# mdimport
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mdimport.1
complete -c mdimport -s i --description 'Request Spotlight to import file or recursively import directory.'
complete -c mdimport -s t --description 'Request Spotlight to test import file, sending the result back to mdimport md…'
complete -c mdimport -s d --description 'Print debugging information.   This requires t.  -literal -offset indent.'
complete -c mdimport -o d1 --description 'print summary of test import.'
complete -c mdimport -o d2 --description 'print summary of import and all attributes, except kMDItemTextContent.'
complete -c mdimport -o d3 --description 'print summary of import and all attributes Ed.'
complete -c mdimport -s o --description 'Store attribute into outfile.  This requires t.'
complete -c mdimport -s p --description 'Print out performance information gathered during the run.   This requires t.'
complete -c mdimport -s A --description 'Print out the list of all of the attributes and their localizations in the cu…'
complete -c mdimport -s X --description 'Print the schema file and exit.'
complete -c mdimport -s L --description 'Print the list of installed importers and exit.'
complete -c mdimport -s r --description 'Ask the server to reimport files for UTIs claimed by the listed plugin.'

