# mdutil
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mdutil.1
complete -c mdutil -s i --description 'Sets the indexing status for the provided volumes to on or off.'
complete -c mdutil -s d --description 'Disables Spotlight searches on the provided volume.'
complete -c mdutil -s E --description 'This flag will cause each local store for the volumes indicated to be erased.'
complete -c mdutil -s s --description 'Display the indexing status of the listed volumes.'
complete -c mdutil -s a --description 'Apply command to all stores on all volumes.'
complete -c mdutil -s t --description 'Resolve files from file id with an optional volume path or device id.'
complete -c mdutil -s p --description 'Spotlight caches indexes of some network devices locally.'
complete -c mdutil -s V --description 'Apply command to all stores on the specified volume.'
complete -c mdutil -s v --description 'Print verbose information when available.'
complete -c mdutil -s r --description 'Ask the server to reimport files for UTIs claimed by the listed plugin.'
complete -c mdutil -s L --description 'List the directory contents of the Spotlight index on the specified volume.'
complete -c mdutil -s P --description 'Dump the VolumeConfig. plist for the specified volume.'
complete -c mdutil -s X --description 'Remove the Spotlight index directory on the specified volume.'

