# mkfifo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mkfifo.1
complete -c mkfifo -s m --description 'Set the file permission bits of newly-created fifos to mode, without respect …'

