# mkfile
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/mkfile.8
complete -c mkfile -s n --description 'Create an empty R filename .'
complete -c mkfile -s v --description 'Verbose.   Report the names and sizes of created files.'

