# mklocale
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/mklocale.1
complete -c mklocale -s d --description 'Turns on debugging messages.'
complete -c mklocale -s o --description 'Specify output file.'

