# navtesttool
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/navtesttool.1
complete -c navtesttool -s a --description 'Description of -a flag.'
complete -c navtesttool -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

