# nettop
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/nettop.1
complete -c nettop -s m --description 'Specify the mode.  By default, nettop will monitor TCP and UDP sockets.'
complete -c nettop -s t --description 'Specify the type of interface.  By default, all interfaces will be monitored.'
complete -c nettop -s n --description 'Disable address to name resolution.'
complete -c nettop -s c --description 'Less intensive use of the CPU - draws less often.'
complete -c nettop -s d --description 'Delta mode.'
complete -c nettop -s x --description 'Extended display of numbers instead of human readable suffixes such as MiB.'
complete -c nettop -s P --description 'Display per-process summary only, skipping details of open connections.'
complete -c nettop -s s --description 'Set the delay between updates to <delay> seconds.'
complete -c nettop -s l --description 'Use  logging  mode  and  display  <samples> samples, even if standard output …'
complete -c nettop -s L --description 'Use  logging  mode  and  display  <samples> samples, even if standard output …'
complete -c nettop -s p --description 'Select a process for display.'
complete -c nettop -s j --description 'Specifiy a list of column headings to be included in the display.'
complete -c nettop -s J --description 'Specifiy a list of column headings that are to be the only ones included in t…'
complete -c nettop -s k --description 'Specifiy a list of column headings to be excluded from the display.'

