# PasswordService
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/PasswordService.8
complete -c PasswordService -s n --description 'Do not daemonize.'

