# paste
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/paste.1
complete -c paste -s d --description 'Use one or more of the provided characters to replace the newline characters …'
complete -c paste -s s --description 'Concatenate all of the lines of each separate input file in command line orde…'

