# pathchk
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pathchk.1
complete -c pathchk -s p --description 'Perform portability checks on the specified pathname arguments.'

