# pfbtops
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pfbtops.1
complete -c pfbtops -s v --description 'Print the version number.  SEE ALSO grops (1).'

