# pod2text5
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/pod2text5.28.1
complete -c pod2text5 -l errors --description 'Set the error handling style.'

