# postlock
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/postlock.1
complete -c postlock -s c --description 'Read the main.'
complete -c postlock -s l --description 'Override the locking method specified via the mailbox_delivery_lock configura…'
complete -c postlock -s v --description 'Enable verbose logging for debugging purposes.'

