# ppdi
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ppdi.1
complete -c ppdi -s I --description 'Specifies an alternate include directory.'
complete -c ppdi -s o --description 'Specifies the PPD source file to update.'

