# ppdmerge
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/ppdmerge.1
complete -c ppdmerge -s o --description 'Specifies the PPD file to create.'

