# printtool
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/printtool.8
complete -c printtool -l reset --description 'Reset the printing system.'
complete -c printtool -s f --description 'Do not prompt for confirmation FILES /System/Library/Frameworks/ApplicationSe…'

