# quota
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/quota.1
complete -c quota -s g --description 'Print group quotas for the group of which the user is a member.'
complete -c quota -s v --description 'quota quota will display quotas on filesystems where no storage is allocated.'
complete -c quota -s q --description 'Print a more terse message, containing only information on filesystems where …'

