# remindd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/remindd.8
complete -c remindd -s a --description 'Description of -a flag.'
complete -c remindd -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

