# rmiregistry
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/rmiregistry.1
complete -c rmiregistry -s J --description 'Used in conjunction with any java option, this option passes option (no space…'

