# rpcbind
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/rpcbind.8
complete -c rpcbind -s d --description 'causes rpcbind errors and debugging information to be printed to the standard…'
complete -c rpcbind -s v --description 'Enable verbose logging of access control checks.'
complete -c rpcbind -s h --description 'Specify specific IP addresses to bind to for UDP requests.'

