# safaridriver
# Autogenerated from man page /Library/Apple/usr/share/man/man1/safaridriver.1
complete -c safaridriver -s p --description 'Specifies the port on which the HTTP server should listen for incoming connec…'
complete -c safaridriver -s h --description 'Prints a usage message and exits.'
complete -c safaridriver -o '\\-version' --description 'Prints version information and exits.'
complete -c safaridriver -o '\\-enable' --description 'Applies configuration changes so that subsequent WebDriver sessions will run …'
complete -c safaridriver -o '\\-diagnose' --description 'Enables diagnostic logging for all sessions hosted by this safaridriver insta…'

