# segedit
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/segedit.1
complete -c segedit -o extract --description 'Extracts each section specified by the segment and section names and places t…'
complete -c segedit -o replace --description 'Replaces each section specified by the segment and section names and takes th…'
complete -c segedit -o sectcreate --description 'option.'
complete -c segedit -s l --description 'option to otool (1).'
complete -c segedit -o output --description 'option must also be specified.'

