# smtpd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/smtpd.8
complete -c smtpd -o bs --description '$mail_owner privileges, it receives mail even while the mail system is not ru…'
complete -c smtpd -s V --description 'and later.'

