# stapler
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/stapler.1
complete -c stapler -s q --description 'When validating or attaching tickets, stapler will only return the exit code.'
complete -c stapler -s v --description 'Sets the output of stapler to include additional diagnostic output.'

