# umtest
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/umtest.1
complete -c umtest -s a --description 'Description of -a flag.'
complete -c umtest -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

