# unexpand
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/unexpand.1
complete -c unexpand -s a --description 'unexpand ( unexpand only.'
complete -c unexpand -s t --description 'Set tab stops at column positions tab1 , tab2 , .  , tabn.'

