# vtool
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/vtool.1
complete -c vtool -o arch --description 'Specifies the architecture, arch, for vtool to operate on when the file is a …'
complete -c vtool -s h --description 'Print full usage.'
complete -c vtool -s o --description 'Commands that create new files write to the out_file file specified by the ou…'
complete -c vtool -s r --description 'When used with set-build-version or set-version-min the replace option instru…'
complete -c vtool -o remove-build-tool --description 'Removes tool from the platform build version.'
complete -c vtool -o remove-build-version --description 'Removes the build version for the specified platform.'
complete -c vtool -o remove-source-version --description 'Removes the source version from the Mach-O file.  Must be used with output.'
complete -c vtool -o set-build-tool --description 'Updates the build version load command for platform to include the specified …'
complete -c vtool -o set-build-version --description 'Create or update the LC_BUILD_VERSION load command for platform to include th…'
complete -c vtool -o set-source-version --description 'Create or update the source version load command.  version takes the format A.'
complete -c vtool -o set-version-min --description 'Create or update an LC_VERSION_MIN_* load command for platform.'
complete -c vtool -o show --description 'Display the build and source versions within the specified file.'
complete -c vtool -o show-build --description 'Display the build versions within the specified file.'
complete -c vtool -o show-source --description 'Display the source version within the specified file.'
complete -c vtool -o show-space --description 'Show the space in the file consumed by the mach header and the existing load …'

