# w
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man1/w.1
complete -c w -s h --description 'Suppress the heading.'
complete -c w -s i --description 'Output is sorted by idle time.'

