# wspd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/wspd.8
complete -c wspd -l s --description 'The UNIX socket wspd listens to.'
complete -c wspd -l d --description 'The delay between last connection was disconnected and the time wspd will clo…'

